name: Generate Contribution Calendar

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Contribution Calendar
        uses: lowlighter/metrics@latest
        with:
          user: Balu143865
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
