name: Contribution Calendar

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Contribution Calendar
        uses: seijikohara/profile-cards-action@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: Balu143865
          cards: contributions
          output-dir: assets
          themes: light,dark
          commit: true
          commit-message: "Update contribution calendar"
