name: Contribution Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Generate Contribution Calendar
        uses: seijikohara/profile-cards-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: Balu143865
          cards: contributions
          output-dir: assets
          themes: light,dark
          commit: true
          commit-message: "chore: update contribution calendar"
